# Generated by Django 3.2.16 on 2023-02-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.CharField(db_index=True, default=12, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='photo',
            index_together={('id', 'slug')},
        ),
    ]
