# Generated by Django 3.2.16 on 2023-02-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0003_auto_20230218_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.SlugField(default=12, max_length=130, unique=True),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='photo',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
    ]
