# Generated by Django 3.2.16 on 2023-02-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0004_auto_20230218_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
    ]
