# Generated by Django 3.2.16 on 2023-02-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0005_remove_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='image',
            new_name='photo',
        ),
    ]
