# Generated by Django 3.2.16 on 2023-02-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0006_rename_image_reviews_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
    ]
