# Generated by Django 3.2.16 on 2023-02-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0007_remove_reviews_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Comments',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='file_reviews',
            new_name='file_comments',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='image_reviews',
            new_name='image_comments',
        ),
    ]
