# Generated by Django 3.2.16 on 2023-02-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0008_auto_20230219_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='file_comments',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='image_comments',
        ),
    ]
