# Generated by Django 3.2.16 on 2023-02-19 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0010_auto_20230219_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='photo_comments',
            field=models.ImageField(upload_to='receipts/%Y/%m/%D', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif'])]),
        ),
    ]
