# Generated by Django 3.2.16 on 2023-02-19 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0011_alter_comments_photo_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='file_comments',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='photo_comments',
            field=models.ImageField(blank=True, upload_to='receipts/%Y/%m/%D', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif'])]),
        ),
    ]
