# Generated by Django 3.2.16 on 2023-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0012_auto_20230219_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='file_comments',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
